language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - hhvm
  - nightly

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  - phpenv config-rm xdebug.ini || true

install: travis_retry composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit